### ISSUE TITLE
Brainrender version 1.0.0.2

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/brainrender#104]
To do list for next `brainrender` version.

- [x] fix `get_camera_params` functionality [see here](https://github.com/BrancoLab/brainrender/issues/100)
- [x] implement new vedo `ruler` object to measure distances to targets (e.g. for probe implants) [see here](https://github.com/marcomusy/vedo/releases/tag/2020.4.0)
- [x] finish PR (https://github.com/BrancoLab/brainrender/pull/99) for zebra fish neurons + Docs
- [x]  make compatible with python > 3.7. Current problems
- [x] implement new axes styles [see here](https://github.com/BrancoLab/brainrender/issues/101)
- [x] improve look of new axes. (e.g. more like ruler axes? ).

- [ ] make origin consistent with rest of BG workflow [see here](https://github.com/brainglobe/bg-atlasapi/issues/73) | also usenew `atals.shape_um` argument to get volume shape.
       - add option to disable the mirroring behaviour: not all custom atlases might need it
       - check that this works with all BG atlasapi atlases

- [ ] Document notebooks better (https://github.com/BrancoLab/brainrender/issues/111)

- [ ] Add actors list report

- [ ] update requirements

- [x] fix verbosity: https://github.com/BrancoLab/brainrender/issues/113

- [ ] testing + docs update
       - compatible with python >3.7 
       - allen sdk optional
       - update `camera` docs.
       - `Ruler`: docs,
       - Mpin docs
        - axes transform docs
       - new axes style ?
      - new scene special attributes

**Comment by FedeClaudi** [comment]
Hi @marcomusy  sorry to bother you, I was just wandering if you have an ETA for the next `vedo` release? Some of the functionality in the next `brainrender` release depends on fixes that are currently just on the github version so I am waiting for that before finilizing the release here. Thanks :)

**Comment by marcomusy** [comment]
1 or 2 days! sorry - i've been busy lately so everything got delayed..

**Comment by FedeClaudi** [comment]
No worries at all! It's your package and you can release stuff when you want and can!
I just wanted to touch base, partly as a reminder to myself :)

**Comment by FedeClaudi** [comment]
Hey, I was trying to install from master with `pip install git+https://github.com/marcomusy/vedo.git -U` but I get an error:
```
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Federico\.conda\envs\dev\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Federico\\AppData\\Local\\Temp\\pip-req-build-1k8izdc5\\setup.py'"'"'; __file__='"'"'C:\\Users\\Federico\\AppData\\Local\\Temp\\pip-req-build-1k8izdc5\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Federico\AppData\Local\Temp\pip-pip-egg-info-n4ecdsvy'
         cwd: C:\Users\Federico\AppData\Local\Temp\pip-req-build-1k8izdc5\
    Complete output (8 lines):
    running egg_info
    creating C:\Users\Federico\AppData\Local\Temp\pip-pip-egg-info-n4ecdsvy\vedo.egg-info
    writing C:\Users\Federico\AppData\Local\Temp\pip-pip-egg-info-n4ecdsvy\vedo.egg-info\PKG-INFO
    writing dependency_links to C:\Users\Federico\AppData\Local\Temp\pip-pip-egg-info-n4ecdsvy\vedo.egg-info\dependency_links.txt
    writing requirements to C:\Users\Federico\AppData\Local\Temp\pip-pip-egg-info-n4ecdsvy\vedo.egg-info\requires.txt
    writing top-level names to C:\Users\Federico\AppData\Local\Temp\pip-pip-egg-info-n4ecdsvy\vedo.egg-info\top_level.txt
    writing manifest file 'C:\Users\Federico\AppData\Local\Temp\pip-pip-egg-info-n4ecdsvy\vedo.egg-info\SOURCES.txt'
    error: supposed package directory 'vedo\examples' exists, but is not a directory

```

any idea? Do you have a pre-release version I can install from pip?

**Comment by FedeClaudi** [comment]
never mind it seems that I screwed something up on my machine...

**Comment by marcomusy** [comment]
oh actually this is very enlightening as it might be related to https://github.com/marcomusy/vedo/issues/185

**Comment by FedeClaudi** [comment]
Could be... but I can't install also my forked version that worked previously for me. I'm on windows now and I had tested it on mac though, so maybe it's a windows issue?

**Comment by marcomusy** [comment]
not sure.. I need to investigate - might be due to a newer python/pip version that doesn't like symlinks (?)

**Comment by marcomusy** [comment]
i've been able to reproduce the issue on a windows OS - so i'm on the track to find a better solution in the `setup.py`.

**Comment by FedeClaudi** [comment]
I see, thanks for keeping me posted.

Meanwhile, I've tested it on Mac and it works fine :)

**Comment by FedeClaudi** [comment]
It's out!
https://github.com/brainglobe/brainrender/releases/tag/1.0.1.0
